CLASS zcl_minesweeper DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.

    METHODS annotate
        IMPORTING
          !input        TYPE string_table
        RETURNING
          VALUE(result) TYPE string_table.

ENDCLASS.

CLASS zcl_minesweeper IMPLEMENTATION.

  METHOD annotate.
    LOOP AT INPUT ASSIGNING FIELD-SYMBOL(<FS_INPUT>).
      DATA(LEN_LINE) = STRLEN( <FS_INPUT> ).
      DATA(LV_TABIX) = SY-TABIX.
      DO LEN_LINE TIMES.
        DATA(LV_INDEX) = SY-INDEX - 1.
        IF <FS_INPUT>+LV_INDEX(1) <> '*'.
    
          DATA(MINUSONE) = LV_INDEX - 1.
          DATA(PLUSONE) = LV_INDEX + 1.
          DATA(UPSTAIRS) = VALUE STRING( INPUT[ LV_TABIX - 1 ] OPTIONAL ).
          DATA(DOWNSTAIRS) = VALUE STRING( INPUT[ LV_TABIX + 1 ] OPTIONAL ).
    
          DATA(LEFT) = COND #( WHEN MINUSONE >= 0 AND <FS_INPUT>+MINUSONE(1) = '*' THEN 1 ELSE 0 ).
          DATA(RIGHT) = COND #( WHEN PLUSONE < LEN_LINE AND <FS_INPUT>+PLUSONE(1) = '*' THEN 1 ELSE 0 ).
          DATA(TOP) = COND #( WHEN UPSTAIRS IS NOT INITIAL AND UPSTAIRS+LV_INDEX(1) = '*' THEN 1 ELSE 0 ).
          DATA(TOPLEFT) = COND #( WHEN UPSTAIRS IS NOT INITIAL AND MINUSONE >= 0 AND UPSTAIRS+MINUSONE(1) = '*' THEN 1 ELSE 0 ).
          DATA(TOPRIGHT) = COND #( WHEN UPSTAIRS IS NOT INITIAL AND PLUSONE < LEN_LINE AND UPSTAIRS+PLUSONE(1) = '*' THEN 1 ELSE 0 ).
          DATA(BOTTOM) = COND #( WHEN DOWNSTAIRS IS NOT INITIAL AND DOWNSTAIRS+LV_INDEX(1) = '*' THEN 1 ELSE 0 ).
          DATA(BOTTOMLEFT) = COND #( WHEN DOWNSTAIRS IS NOT INITIAL AND MINUSONE >= 0 AND DOWNSTAIRS+MINUSONE(1) = '*' THEN 1 ELSE 0 ).
          DATA(BOTTOMRIGHT) = COND #( WHEN DOWNSTAIRS IS NOT INITIAL AND PLUSONE < LEN_LINE AND DOWNSTAIRS+PLUSONE(1) = '*' THEN 1 ELSE 0 ).
    
          DATA(TOTAL) = RIGHT + LEFT + TOP + BOTTOM + TOPLEFT + TOPRIGHT + BOTTOMLEFT + BOTTOMRIGHT.
          IF TOTAL > 0.
              <FS_INPUT> = REPLACE( VAL = <FS_INPUT> 
                                    OFF = LV_INDEX 
                                    WITH  = TOTAL 
                                    LEN = 1 ).
          ENDIF.
          CLEAR: TOTAL, RIGHT, LEFT, TOP, BOTTOM, TOPLEFT, TOPRIGHT, BOTTOMLEFT, BOTTOMRIGHT, UPSTAIRS, DOWNSTAIRS, MINUSONE, PLUSONE.
        ENDIF.
      ENDDO.
    ENDLOOP.
    RESULT = INPUT.
  ENDMETHOD.

ENDCLASS.
