CLASS zcl_secret_handshake DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPES: CHAR5(5)   TYPE C.
    METHODS get_commands
      IMPORTING code            TYPE i
      RETURNING VALUE(commands) TYPE string_table.
  PROTECTED SECTION.
  PRIVATE SECTION.
    METHODS DECTOBIN
      IMPORTING CODE          TYPE I
      RETURNING VALUE(BINARY) TYPE CHAR5.
ENDCLASS.



CLASS ZCL_SECRET_HANDSHAKE IMPLEMENTATION.
  METHOD GET_COMMANDS.
    DATA(SECRET_CODES) = VALUE STRING_TABLE( ( 'wink' ) ( 'double blink' ) ( 'close your eyes' ) ( 'jump' ) ).
    DATA(BINARY) = DECTOBIN( CODE ).
    DO 4 TIMES.
      DATA(OFFSET) = 5 - SY-INDEX.
      DATA(TABINDEX) = COND  #( WHEN BINARY+0(1) = '0' THEN LINES( COMMANDS ) + 1 ELSE 1 ).
      IF BINARY+OFFSET(1) = '1'.
        INSERT SECRET_CODES[ SY-INDEX ] INTO COMMANDS INDEX TABINDEX.
      ENDIF.
    ENDDO.
  ENDMETHOD.

  METHOD DECTOBIN.
    WHILE CODE > 0.
      BINARY = |{ BINARY }{ CODE MOD 2 }|.
      CODE = COND #( WHEN CODE MOD 2 = 0 THEN CODE / 2 ELSE ( CODE / 2 ) - 1 ).
    ENDWHILE.
*    TRANSLATE RETURN USING ' 0'. "YOU CAN USE THIS INSTEAD OF THE LOOP BELOW BUT EXERCISM DID NOT ACCEPT. 
    BINARY =  REVERSE( BINARY ).
    DO 5 - STRLEN( BINARY ) TIMES.
      BINARY = |0{ BINARY }|.
    ENDDO.
  ENDMETHOD.
ENDCLASS.